[package]
name = "liftkata"
version = "0.1.0"
authors = ["elieser pereira <elieser.pereiraa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
